version: "3.8"

services:
  server:
    build:
      context: .
      args: 
        NODE_ENV: ${NODE_ENV}
    container_name: 25_1_main-backend
    env_file:
      - .env
    ports:
      - 3001:3001
    depends_on:
      db:
        condition: service_healthy  # MySQL이 정상 실행된 후 시작
    networks:
      - mynetwork  

  db:
    image: mysql:8.0
    container_name: 25_1_main-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DEV_DB_PASSWORD}  
      MYSQL_DATABASE: ${DEV_DB_NAME}          
      MYSQL_USER: ${DEV_DB_USER}              
      MYSQL_PASSWORD: ${DEV_DB_PASSWORD}
    ports:
      - "3307:3306"  # MySQL 컨테이너는 3306에서 실행되지만, 로컬에서는 3307로 접근
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork
    healthcheck:  # MySQL 완전 부팅 확인 후 백엔드 실행
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:

networks:
  mynetwork:  # 네트워크 명시적으로 정의
    name: mynetwork  # 자동으로 생성되는 이름을 `mynetwork`로 고정
    driver: bridge
